name: docker 

# Allow repository modyfication;
permissions:
  contents: write
  pull-requests: write

on:
  # Allow to re-use this jobs;
  workflow_call:
  # Trigger minor update;
  # Trigger patch update;
  push:
  # Trigger major update;
  workflow_dispatch:
  packages: write


jobs:

# -----------------
# SEMVER 
# -----------------

  semver:
    uses: utilizable/github-actions-semver-tagging/.github/workflows/semver.yml@feat/output

# -----------------
# DOCKER BUILDING
# -----------------

  building:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{needs.semver.outputs.output1}} 
#    uses: utilizable/github-actions-docker-building/.github/workflows/building.yml@develop
